import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const translations = {
    en: {
      home: 'Home',
      schedules: 'Schedules',
      status: 'Status',
      login: 'Login',
      logout: 'Logout',
      dashboard: 'Dashboard',
      complaints: 'Complaints',
      submitComplaint: 'Submit Complaint',
      ourPrograms: 'Our Programs',
      completedPrograms: 'Completed Programs',
      contact: 'Contact',
      address: 'Address',
      phone: 'Phone',
      email: 'Email',
      quote1: 'సమాజమే దేవాలయం, ప్రజలే దేవుళ్ళు',
      quote2: 'జనం కోసం జనార్ధన్',
      welcome: 'Welcome',
      mlaName: 'Damacharla Janardhana Rao',
      constituency: 'MLA-Ongole constituency',
      slogan: 'Service to the People is Service to God',
      forThePeople: 'For the People',
      byThePeople: 'By the People',
      permanent: 'Keep Permanently',
      submit: 'Submit',
      cancel: 'Cancel',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      view: 'View',
      close: 'Close',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      pending: 'Pending',
      inProgress: 'In Progress',
      resolved: 'Resolved',
      rejected: 'Rejected',
      subject: 'Subject',
      description: 'Description',
      category: 'Category',
      village: 'Village',
      mandal: 'Mandal',
      date: 'Date',
      location: 'Location',
      title: 'Title',
      actions: 'Actions',
      noData: 'No data available',
      welcomeBack: 'Welcome Back',
      pleaseLogin: 'Please login to continue',
      password: 'Password',
      name: 'Full Name',
      register: 'Register',
      alreadyHaveAccount: 'Already have an account?',
      dontHaveAccount: "Don't have an account?",
      signUp: 'Sign Up',
      signIn: 'Sign In',
      adminPanel: 'Admin Panel',
      manageSchedules: 'Manage Schedules',
      manageComplaints: 'Manage Complaints',
      addSchedule: 'Add Schedule',
      myComplaints: 'My Complaints',
      newComplaint: 'New Complaint',
      infrastructure: 'Infrastructure',
      water: 'Water',
      electricity: 'Electricity',
      roads: 'Roads',
      healthcare: 'Healthcare',
      education: 'Education',
      other: 'Other',
      uploadImage: 'Upload Image',
      uploadGallery: 'Upload Gallery',
      primaryImage: 'Primary Image',
      coverBanner: 'Cover Banner',
      upcoming: 'Upcoming',
      completed: 'Completed',
      ongoing: 'Ongoing',
      cancelled: 'Cancelled',
    },
    te: {
      home: 'హోమ్',
      schedules: 'షెడ్యూల్స్',
      status: 'స్థితి',
      login: 'లాగిన్',
      logout: 'లాగ్అవుట్',
      dashboard: 'డాష్‌బోర్డ్',
      complaints: 'ఫిర్యాదులు',
      submitComplaint: 'ఫిర్యాదు దాఖలు చేయండి',
      ourPrograms: 'మా కార్యక్రమాలు',
      completedPrograms: 'పూర్తయిన కార్యక్రమాలు',
      contact: 'సంప్రదింపు',
      address: 'చిరునామా',
      phone: 'ఫోన్',
      email: 'ఇమెయిల్',
      quote1: 'సమాజమే దేవాలయం, ప్రజలే దేవుళ్ళు',
      quote2: 'జనం కోసం జనార్ధన్',
      welcome: 'స్వాగతం',
      mlaName: 'దామచర్ల జనార్ధన రావు',
      constituency: 'MLA-Ongole constituency',
      slogan: 'ప్రజల సేవే దేవుడి సేవ',
      forThePeople: 'ప్రజల కోసం',
      byThePeople: 'ప్రజలతో',
      permanent: 'శాశ్వతంగా ఉంచండి',
      submit: 'సమర్పించండి',
      cancel: 'రద్దు చేయండి',
      save: 'సేవ్ చేయండి',
      delete: 'తొలగించండి',
      edit: 'సవరించండి',
      view: 'చూడండి',
      close: 'మూసివేయండి',
      loading: 'లోడ్ అవుతోంది...',
      error: 'లోపం',
      success: 'విజయం',
      pending: 'పెండింగ్',
      inProgress: 'పురోగతిలో ఉంది',
      resolved: 'పరిష్కరించబడింది',
      rejected: 'తిరస్కరించబడింది',
      subject: 'విషయం',
      description: 'వివరణ',
      category: 'వర్గం',
      village: 'గ్రామం',
      mandal: 'మండలం',
      date: 'తేదీ',
      location: 'స్థలం',
      title: 'శీర్షిక',
      actions: 'చర్యలు',
      noData: 'డేటా లేదు',
      welcomeBack: 'మళ్ళీ స్వాగతం',
      pleaseLogin: 'కొనసాగించడానికి దయచేసి లాగిన్ చేయండి',
      password: 'పాస్‌వర్డ్',
      name: 'పూర్తి పేరు',
      register: 'నమోదు',
      alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
      dontHaveAccount: 'ఖాతా లేదా?',
      signUp: 'సైన్ అప్',
      signIn: 'సైన్ ఇన్',
      adminPanel: 'అడ్మిన్ ప్యానెల్',
      manageSchedules: 'షెడ్యూల్స్ నిర్వహించండి',
      manageComplaints: 'ఫిర్యాదులను నిర్వహించండి',
      addSchedule: 'షెడ్యూల్ జోడించండి',
      myComplaints: 'నా ఫిర్యాదులు',
      newComplaint: 'కొత్త ఫిర్యాదు',
      infrastructure: 'మౌలిక సదుపాయాలు',
      water: 'నీరు',
      electricity: 'విద్యుత్',
      roads: 'రోడ్లు',
      healthcare: 'ఆరోగ్య సంరక్షణ',
      education: 'విద్య',
      other: 'ఇతర',
      uploadImage: 'చిత్రాన్ని అప్‌లోడ్ చేయండి',
      uploadGallery: 'గ్యాలరీని అప్‌లోడ్ చేయండి',
      primaryImage: 'ప్రాధమిక చిత్రం',
      coverBanner: 'కవర్ బ్యానర్',
      upcoming: 'రాబోయే',
      completed: 'పూర్తయిన',
      ongoing: 'కొనసాగుతోంది',
      cancelled: 'రద్దు చేయబడింది',
    }
  };

  const t = (key) => translations[language][key] || key;

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'te' : 'en');
  };

  return (
    <LanguageContext.Provider value={{ language, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};
